### PR TITLE
Incorporates SConstruct patches from MacPorts

### PR DESCRIPTION
**Pull request by fhgwright**
This branch contains three patches originally from the MacPorts build (with applicability beyond MacPorts and even beyond the Mac), plus a tab cleanup patch.  See the individual commit descriptions for more details.

### CODE REVIEW

**Comment by fhgwright** [comment]
Added one more commit to fix the 10.4 build.

**Comment by yazug** [comment]
Cherry-picked a couple of these and also did some additional General cleanup of SConstruct.

I want to check the versioned Qt library building locally before I feel comfortable pushing the remaining changes.  Also the dbus linking issue I was thinking the LIBPATH stuff was done to avoid pulling in old versions of gpsd libraries if they were installed on the system, but I do agree it doesn't quite seem sane to squash all other lib path entries with that change if that's what's happening.

**Comment by yazug** [comment]
also the LIBPATH has a possiblity that's it interactions between LIBPATH variable passed in and parse_flags which should be pulling in the library paths for dbus, usblib, rtlibs ... if we are missing more or if a LIBPATH is passed in that has access to the libraries required then I can see that change causing issues.  More debugging will be needed to get to the bottom of that issue with out causing regressions in other build environments.  as it currently stands there is a regression for MacPorts and possibly others.  Would like any feedback as to how the paths for the dbus are arranged.  On my system if I recall correctly it was correctly passed in via parse_args and the dbus library was not on the system path.

**Comment by fhgwright** [comment]
On qt_versioned:

I admit I didn't test that feature on platforms other than OSX, and also that I didn't test that the Qt support actually _works_ (only that it builds), but it's clear from the examples on the Qt website that Qt5 has renamed the libraries from QtXXX to Qt5XXX, so the need for the prefix tweak isn't OSX-specific.  It's also a safe change in that the default setting doesn't change the current behavior (except for not checking for the existence of QtNetwork in the case where it has no intention of actually using it :-)).

ISTR that there's a Qt-based xgps-like program kicking around somewhere - it might be useful to pull it into contrib for testing the Qt support.

On LIBPATH:

The dbus logic is unique in that it puts the needed options into LIBPATH via MergeFlags, while the other similar features set up separate variables that are supplied in appropriate cases via parse_flags, so they're immune to the LIBPATH='.' tweaks.  If dbus worked the same way (which might make sense), then the LIBPATH tweak would become a don't-care for dbus as well, though I believe it would still break sysroot-based cross-building.  And even if it were completely a NOP, it would still be unnecessary clutter.

"I was thinking the LIBPATH stuff was done to avoid pulling in old versions of gpsd libraries if they were installed on the system"
But that could only apply to libraries not in the current directory, since the constructed LIBPATH also has the current directory as its first entry.

If you have access to build environments other than the 13 I tested, feel free to try it.  I think you'll find that it works with LIBPATH='.' removed, and may or may not fail dbus linking with it present, depending on where the dbus libraries live.

BTW, building with ncurses is also broken on all BSD variants I tried (Free, Open and Net), though for different reasons in each case.  I'll take a look at that at some point, but probably not right away.

FYI - the only SConstruct patch from MacPorts not covered here is a one-line addition whose necessity I have yet to confirm (across 7 different OSX versions).

**Comment by fhgwright** [comment]
Since all but one of these commits has already been merged into the main Savannah repo, and the one remaining commit will probably be handled there as well, I'm closing this pull request.

I rebased this branch to the current state of master on Savannah (two commits ahead of yazug:master), so it only reflects the unmerged commit.

**Pull request closed without merging**
